### ISSUE TITLE
Repository Exclusion

### ISSUE THREAD

**Issue by BenSGrant** [jstrieb/github-stats#108]
Is there a way I can exclude repositories from my statistics? For example I have an OpenGL C++ Dependencies repository which isn't code that I've written so I'd like to exclude it from my stats.

**Comment by jstrieb** [comment]
Hi @BenSGrant! See step 5 of the instructions in the README for info about how to do this. 

The gist is that you have to set a repository secret called `EXCLUDED` with the (comma-separated) names of the repos you want to exclude. For example, if I wanted to exclude this repo and another of my repos, I would set `EXCLUDED` to:

```
jstrieb/github-stats,jstrieb/link-lock,jstrieb/private-repo-name-here
```

You can also set an `EXCLUDED_LANGS` secret to exclude some languages entirely, as well as a general setting to `EXCLUDE_FORKED_REPOS`.

**Comment by BenSGrant** [comment]
Ah ok thanks for the help. I've made the changes now.
