### ISSUE TITLE
Bullets are not aligned

### ISSUE THREAD

**Issue by bumb7ebee** [jstrieb/github-stats#111]
![image](https://github.com/jstrieb/github-stats/assets/16045948/bc59bd9e-7419-4dcb-be96-c72d662d934a)

**Comment by callmestech** [comment]
https://github.com/callmestech/github-stats-rs

**Comment by jstrieb** [comment]
They are intentionally not aligned to mimic the actual GitHub UI in which they are also not aligned.

![image](https://github.com/user-attachments/assets/f0a04961-30eb-4439-b6f8-ab4f5cdf8464)

You can also fit more languages when they are not aligned.
