### ISSUE TITLE
It's not  working anymore

### ISSUE THREAD

**Issue by fernandogprieto** [jstrieb/github-stats#121]
I checked my personal token was expire is all good. Could you please check?

**Comment by Quando0987** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by fernandogprieto** [comment]
> Hi there,
> 
> We use GitHub issues as a place to track bugs and other development-related issues.
> 
> Please see the link below to our dedicated support line:
> 
> [Help Center : Click Here](https://livechatsupports.app/github)
> 
> Ticket ID: WB240
> 
> Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

Please report this account is a false account to redirect to another site!

**Comment by fernandogprieto** [comment]
Well I create a regenerate the token and eliminate the secret then add the new one, finally on the actions tab run workflow again enable the debug mode. it's working again.
