### ISSUE TITLE
Shouldn't the env variable be "EXCLUDED_LANGS"?

### ISSUE THREAD

**Issue by JoseDeFreitas** [jstrieb/github-stats#23]
Hello 👋.

I'm opening this issue because I have some problems while adding excluded languages to my fork's secrets. I added them just as the instruction says; however, when I ran the workflow, the `languages.svg` file didn't get updated, but the `overview.svg` did. I was reading the code while I noticed that in the [main.yml](https://github.com/jstrieb/github-stats/blob/master/.github/workflows/main.yml) file, at [line 57](https://github.com/jstrieb/github-stats/blob/2775d6460cc3a2840fb405f51e90cc9531aca5ae/.github/workflows/main.yml#L57) it says "`EXCLUDED_LANGS: ${{ secrets.EXCLUDE_LANGS }}`". In the [README](https://github.com/jstrieb/github-stats#readme) file at the point 5 it says that if you want to exclude languages you need to create a secret called `EXCLUDED_LANGS`. I'm not experienced in GitHub Actions, but I guess `secrets.EXCLUDE_LANGS` should match the name of the secret (which, according to the README should be `EXLUDED_LANGS` (with that "D" at the end)). I was about to open a PR but as I'm not sure if that's the case I preferred to open an issue 😅.

**Comment by jstrieb** [comment]
Hey, thanks for spotting the issue and bringing it to my attention! Hopefully this hasn't been affecting others...I can certainly see how it would be frustrating to put in languages and have it not actually exclude them.

If you want to add a "D" to the proper place in line 57 of `main.yml` and make a PR, I will happily merge it! If you'd rather not make a PR, I can make the fix. However if you make the PR and I merge it, you will get credit as a ["contributor"](https://github.com/jstrieb/github-stats/graphs/contributors) to the repo. Either way, just respond here, and I'll handle it accordingly.

Thanks again!

**Comment by JoseDeFreitas** [comment]
Just opened the pull request. Close this issue when you want. Thank you for your quick response!

**Comment by jstrieb** [comment]
Merged and closed. Thanks again!
