### ISSUE TITLE
Still not so convenient 

### ISSUE THREAD

**Issue by PassionPenguin** [jstrieb/github-stats#25]
It still need to add this files to the repo, even to every repo so that the stats can be updated.

But it's possible to checkout another user's repo in GitHub Action...why not just checkout this repo and use the python source files inside?

**Comment by jstrieb** [comment]
Hi! I would love to address your question, but I'm having a hard time understanding what you mean.

Once you make a copy of the repo, it will begin generating the images when you enable the GitHub Action. As far as I know, besides setting secrets, there is no need to copy files to other repositories.

Does this address your question? Thanks!

**Comment by PassionPenguin** [comment]
sorry for that...

i will later open a pr once i finished my code~ :)

**Comment by jstrieb** [comment]
Hello! I've taken a look at the pull request, but am still not sure what the intention is. 

Is the goal to use the GitHub action to generate images in a secondary repository to separate the code and data?

I am still confused, and would appreciate some clarification. Thanks!

**Comment by PassionPenguin** [comment]
> Hello! I've taken a look at the pull request, but am still not sure what the intention is.
> 
> Is the goal to use the GitHub action to generate images in a secondary repository to separate the code and data?
> 
> I am still confused, and would appreciate some clarification. Thanks!

To separate the source code(because this template may not or should not be the main part of another repo.... Separated code to this (jstrieb/github-stats) repo can reduce the unnecessary files and make the structure repo that use this tool clearer)

**Comment by PassionPenguin** [comment]
What i want to:

action=>clone this repo=>run python files and output to the repo that use this tool=>commit that repo

And the only file the user of this tool need to add to their repo is `main.yml` (why not `github-stats.yml` lol)

**Comment by jstrieb** [comment]
Hi! The changes still don't really make sense to me. 

The user should never need to copy any files to use this tool, so I'm not sure what problem the proposed changes solve. The statistics images that are generated are for the user's whole account, not for individual repositories, so if the user has one fork of this repository, that should be all they need. Additional copies would provide the same statistics as the first copy.

Am I still not understanding you, or is it possible you misunderstood part of the project?

**Comment by PassionPenguin** [comment]
> Hi! The changes still don't really make sense to me.
> 
> The user should never need to copy any files to use this tool, so I'm not sure what problem the proposed changes solve. The statistics images that are generated are for the user's whole account, not for individual repositories, so if the user has one fork of this repository, that should be all they need. Additional copies would provide the same statistics as the first copy.
> 
> Am I still not understanding you, or is it possible you misunderstood part of the project?

Yes that's correct, but if i want to use one file from another repo it may be a little more strange, and no matter how the user use this repo, the screen shot below should always be true(the project structure):

<img width="952" alt="Screen Shot 2021-02-25 at 10 01 16 PM" src="https://user-images.githubusercontent.com/41184947/109164102-0022d200-77b5-11eb-96bb-e05afc78238a.png">

The python source file are messy into their branch, and they will need to create a new repo if they want to use the current version, or have to copy both python files and workflow file.

What i want to do is allow the user to just create a new workflow file instead of copying the scripts.

**Comment by PassionPenguin** [comment]
If a user has his or her own repo now, and want to user images for the current one, he has to create a new repo (It's also messy in repo structure, and the HR may have a bad impression on it), or to download this repo and copy all the python source file and workflow file into his repo.

Not everyone wants a new repo, most of us just use it in our Readme.md (github.com/Username/Username), and creating a new repo is not the thing that we want...
