### ISSUE TITLE
Make a note in the README that EXCLUDED must be in the form user/repository

### ISSUE THREAD

**Issue by romdotdog** [jstrieb/github-stats#27]
I thought it was just the name of the repository but it actually is as above. I had to print `name` in the `get_stats` in `github_stats.py` to figure this out.

**Comment by jstrieb** [comment]
Hi! I mention this in the depths of the discussion of a now-closed issue ([here](https://github.com/jstrieb/github-stats/issues/18#issuecomment-776348341)). When I was writing that response, I made a mental note to add more descriptive instructions to the README about this, but ended up forgetting.

Thanks for the reminder! I will make this quick change right now...
