### ISSUE TITLE
Too many stars ?

### ISSUE THREAD

**Issue by bokub** [jstrieb/github-stats#28]
Hi,

I tried your repo, and the result tells me I have **lots** of stars & forks, it's a little bit unrealistic

Are you counting the starts of all repositories I contributed to ?

![image](https://user-images.githubusercontent.com/17952318/109856219-89c11c80-7c59-11eb-9dcb-8ac72a4efaab.png)

I think these are the correct values: 

```
⭐    Total Stars:                            3,183
➕    Total Commits:                          2,512
📦    Contributed to:                            42
```

[source](https://gist.github.com/bokub/1cc900d92b9acc15786d7553b46a2cdf)
[api requests](https://github.com/bokub/github-stats-box/blob/master/fetch.js)

**Comment by jstrieb** [comment]
Hi, thanks for taking a look at the project! By default, the stats counts any repositories you have forked or contributed to. This is likely the cause for the high number of stars/forks. 

To show statistics only for "owned" repositories and not forks with contributions, add an environment variable (under the `env` header in the main workflow) called `EXCLUDE_FORKED_REPOS` with a value of `true`.

**Comment by bokub** [comment]
Ooops it was in the documentation and I didn't read it... Sorry about that !

**Comment by jstrieb** [comment]
No worries! Others have also missed it, which hints to me that it's an area for improvement in the documentation. Thanks again for checking out the project!

**Comment by bokub** [comment]
Maybe you could put it in the env with a `false` value ?
That way, it's easier to notice / change

**Comment by jstrieb** [comment]
Both good ideas! I've added a `false` default value for now, and will sleep on having it be `true` by default.

**Comment by singhayushh** [comment]
It'd be better if this issue is pinned up as well. 
<br />
> To show statistics only for "owned" repositories and not forks with contributions, add an environment variable (under the env header in the main workflow) called EXCLUDE_FORKED_REPOS with a value of true.

This gives an impression that all info of the user's open source contributions will be hidden so I didn't set it to true initially. It was only after reading through this issue that I came to know the number of repos with contributions will still be visible.
