### ISSUE TITLE
Failed to generate images

### ISSUE THREAD

**Issue by pexeixv** [jstrieb/github-stats#30]
I followed the installation guide in README.md. I created a secret with the access token, even then it the log says access token is missing.

```
  python3 --version
  python3 generate_images.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.8/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.8/x64/lib
    ACCESS_TOKEN: 
    GITHUB_TOKEN: ***
    EXCLUDED: 
    EXCLUDED_LANGS: 
    EXCLUDE_FORKED_REPOS: false
Python 3.8.8
Traceback (most recent call last):
  File "generate_images.py", line 119, in <module>
    asyncio.run(main())
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "generate_images.py", line 100, in main
    raise Exception("A personal access token is required to proceed!")
Exception: A personal access token is required to proceed!
Error: Process completed with exit code 1.
```

**Comment by jstrieb** [comment]
Hi, thanks for taking the time to open this issue!

After reading your post, I'm not entirely sure what the problem could be. Have you double checked that you spelled the name of the secret correctly? The place to see the secrets is [here](https://github.com/pexeixv/github-stats/settings/secrets/actions). 

If you provide some more info, we can get to the bottom of what is going wrong, and then I can document the issue for anyone else who might have the same problem.

**Comment by comav** [comment]
Hi!

I had the same issue, so I tried to re-run a workflow, and it worked.
As far as I understand, the script tries to generate images immediately after copying, but you need some time to set a Personal Access Token, so it can't find it.

Hopefully, this will help you

**Comment by jstrieb** [comment]
Thanks @pexeixv and @comav, both for bringing this to my attention, and for identifying the cause (and solution)! I will add this to the main documentation in case there are other users having the same problem who haven't reported it.

**Comment by ArshiaRx** [comment]
> Hi!
> 
> I had the same issue, so I tried to re-run a workflow, and it worked. As far as I understand, the script tries to generate images immediately after copying, but you need some time to set a Personal Access Token, so it can't find it.
> 
> Hopefully, this will help you

Hello, 
Getting back to this how long should we expect to wait until it understands the token and gets updated!

**Comment by Machou** [comment]
Hello 

i have this error :

```
File "generate_images.py", line 105, in main
[22](https://github.com/Machou/github-stats/runs/5990013150?check_suite_focus=true#step:6:22)
    raise Exception("A personal access token is required to proceed!")
[23](https://github.com/Machou/github-stats/runs/5990013150?check_suite_focus=true#step:6:23)
Exception: A personal access token is required to proceed!
[24](https://github.com/Machou/github-stats/runs/5990013150?check_suite_focus=true#step:6:24)
Error: Process completed with exit code 1.
```

i have an ACCESS_TOKEN secret with right for the repo

**Comment by sabirinID** [comment]
Hello, jstrieb!
Why doesn't it display my name/username in the overview section on my README?

Many thanks.
