### ISSUE TITLE
How to show stats in Readme

### ISSUE THREAD

**Issue by UAhmadSoft** [jstrieb/github-stats#34]
My Images are generated in generated Folder but I don't know how to show them in read me file........Plz help me

**Comment by jstrieb** [comment]
Hi! I see you've closed the issue, so I assume you've resolved your problem. I'll respond here in case anyone comes across this in the long-term. Once you have your generated images, you add some Markdown to display the images. There are two ways to do that, both of which work identically:

``` md
![](https://raw.githubusercontent.com/jstrieb/github-stats/master/generated/overview.svg)
![](https://github.com/jstrieb/github-stats/blob/master/generated/languages.svg)
```

Note that only the first type of URL works for general websites, but both ways seem to work for GitHub `README.md` files.

For more reference on how I do this, see my personal profile [`README.md`](https://raw.githubusercontent.com/jstrieb/jstrieb/master/README.md).

**Comment by UAhmadSoft** [comment]
Yes I solved this issue by modifying my ReadMe.md .......Very Thanks for your support

**Comment by UAhmadSoft** [comment]
Yes I solved this issue by modifying my ReadMe.md .......Very Thanks for your support
