### ISSUE TITLE
Commit doesn't work

### ISSUE THREAD

**Issue by yvarim** [jstrieb/github-stats#35]
I followed the readme for the installation and it does work. but once the workflow tries to update, it doesn't work this is the error and i don't really have an idea how i could fix it.

```
Run git config --global user.name "jstrieb/github-stats"
[master 0b12a96] Update generated files
 2 files changed, 34 insertions(+), 115 deletions(-)
To https://github.com/yvarim/github-stats
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/yvarim/github-stats'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Process completed with exit code 1.
```

**Comment by singhayushh** [comment]
Hi there!
By looking at the logs, the commit ID for master `0b12a96` doesn't exist in the remote. I guess there has been some error while configuring the repo. I guess you'll have to delete and redo everything.

Let's see what jstrieb says.

**Comment by jstrieb** [comment]
Hi @yvarim, thanks for taking the time to open this issue! (Also thanks to @singhayushh for the preliminary suggestions.) 

If you give a quick read over #21 does that seem to match the issue you are having? We never got to the bottom of that issue, but it eventually resolved itself. Happy to explore further either way.

**Comment by yvarim** [comment]
After waiting till the next workday i see there has been a new commit in the repo. 

For some reason when i run the workflow manually it does not work but when it runs automatically it can commit to the repo. And that is kinda how i wanted to use it anyways, so for now my issue has been resolved. 

@jstrieb thank you for linking the other issue but just like his issue mine solved itself too. So for now i think we can close this issue and if it stops working completely then we can look further into it

**Comment by jstrieb** [comment]
Thanks for the reply! This is good info I will be sure to raise with anyone who may have this problem in the future. Please do let me know if you get any additional information about what may be going on.
