### ISSUE TITLE
Java Code gets displayed as Kotlin and vice versa 

### ISSUE THREAD

**Issue by suobset** [jstrieb/github-stats#47]
As the title says, the extension counts all my Java code as Kotlin and vice versa. Initially, it did not create this issue (especially when I was coding on Java exclusively), but I started to do some Android Development stuff on Kotlin which messed it up. 

Here's a screenshot from right now:
<img src="https://user-images.githubusercontent.com/73229775/130500387-676f7106-c884-48f6-ba5c-bf8547c7b61f.png"></img><br>

Here's a screenshot from an earlier commit:
<img src="https://user-images.githubusercontent.com/73229775/130500696-a0cc30d3-d1d5-40a7-8f2d-2b8696f024a2.png"></img><br>

I only have one repository in Kotlin, so the latter seems more correct (plus most of my code is still on Java).

**Comment by jstrieb** [comment]
Hi @suobset! Thanks for taking the time to open this issue! 

This is interesting, unexpected behavior. I looked at your profile for examples of repositories that could contributing to this, but I couldn't find any so I assume they're private.

My initial guess is that GitHub internally changed how [github/linguist](https://github.com/github/linguist) determines whether a code file is Java or Kotlin, and this change is reflected in altered results from the API.

Can you see if the "languages" section for each repo is showing Java or Kotlin in the expected proportions? The solution may be adding a [`.gitattributes`](https://github.com/github/linguist/blob/master/docs/overrides.md) file to your Android repos if my suspicion proves correct

**Comment by R055A** [comment]
I have found that when I had a lot of projects in one repository, only so many of the most used languages in this repository were showing in the generated image. Not that I have separated the projects so that they are each in a different repository, all the languages are showing in the generated image.

**Comment by jstrieb** [comment]
> I have found that when I had a lot of projects in one repository, only so many of the most used languages in this repository were showing in the generated image. Now that I have separated the projects so that they are each in a different repository, all the languages are showing in the generated image.

Thanks for documenting this. If this is the root of the problem @suobset is having, then this is likely an issue on GitHub's side. Either way, I'll need a little more info from them to debug.

**Comment by suobset** [comment]
Apologies for the super late response.

I think that is the same problem that I am facing as well. I had a couple of big repositories which were probably causing the issue. When I tried to exclude them from the count, the stats displayed were fine. Similarly, I believe splitting up the repository might have helped in the same way as well. 

Thanks a lot for all your help. I believe that this is a problem from GitHub's side, and thus I'll just close this issue here. 

To anyone else having the issue:

1. Check for big repositories which have a lot of code and/or more than 3-4 recognized languages.
2. Either split those repositories into smaller segments, or exclude them.

**Comment by R055A** [comment]
> Apologies for the super late response.
> 
> I think that is the same problem that I am facing as well. I had a couple of big repositories which were probably causing the issue. When I tried to exclude them from the count, the stats displayed were fine. Similarly, I believe splitting up the repository might have helped in the same way as well.
> 
> Thanks a lot for all your help. I believe that this is a problem from GitHub's side, and thus I'll just close this issue here.
> 
> To anyone else having the issue:
> 
>     1. Check for big repositories which have a lot of code and/or more than 3-4 recognized languages.
> 
>     2. Either split those repositories into smaller segments, or exclude them.

You could check for yourself using this website:

https://docs.github.com/en/graphql/overview/explorer

Otherwise, you could try this modification of jstrieb/github-stats:

https://github.com/R055A/GitStats
