### ISSUE TITLE
Repository views stuck at 0

### ISSUE THREAD

**Issue by sme-ek** [jstrieb/github-stats#67]
I've been using this template for a while now, and never have had any problem with how my repo views are displayed. However, since a recent manual run of the workflow, my repo views have been stuck at 0. I can't work out why this is, because this isn't an accurate number.
Any help would be appreciated.

**Comment by R055A** [comment]
Hi @sme-ek I think you have this repository confused with [R055A/GitStats](https://github.com/r055a/GitStats).

I am unsure why you are not seeing the past 5 days of repository views for your fork of [R055A/GitStats](https://github.com/r055a/GitStats). It may be the repository Secrets you have set in your fork, or it may be the API. If you are going to manually run the workflow then I suggest storing view data and dates to Secrets. Refer to [sme-ek/GitStats#statistics-options](https://github.com/sme-ek/GitStats#statistics-options)

**Comment by sme-ek** [comment]
hey there! unfortunately this problem initially popped up on this repo, which is why i moved to your fork initially. i'll reset some stuff in my repo and see if it helps any. thanks for your response!
