### ISSUE TITLE
Bot Can't Commit

### ISSUE THREAD

**Issue by AfonsoBatista7** [jstrieb/github-stats#69]
### I have done everything you said on the tutorial but it seems like the bot cant have access to the repo...

![image](https://user-images.githubusercontent.com/61472117/166238600-d07273bd-14ff-4a9a-9202-d8ca2421eb47.png)

**Comment by jstrieb** [comment]
Hey @AfonsoBatista7, sorry I was a bit slow to get to this! 

Some others pointed out the issue in #70 so I just wanted to let you know that the problem has been solved. See my response in that thread here: https://github.com/jstrieb/github-stats/issues/70#issuecomment-1120465688.

Thanks for your interest in the project, and for taking the time to report this issue!
