### ISSUE TITLE
Initial commit failed with Error: Process completed with exit code 128.

### ISSUE THREAD

**Issue by tanjuntao** [jstrieb/github-stats#70]
I followed the instructions in the README but the GitHub workflow failed. Here is some information.

### My personal access token permissions
<img width="800" alt="image" src="https://user-images.githubusercontent.com/30660866/167236496-6ed05c3b-09ff-4ce8-a19e-81759783e312.png">

### Step: generate images
```
Run python3 --version
Python 3.8.12
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned [20](https://github.com/tanjuntao/github-stats/runs/6331838497?check_suite_focus=true#step:6:20)2. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
A path returned 202. Retrying...
There were too many 202s. Data for this repository will be incomplete.
```

### Step: commit to the repo
```
Run git config --global user.name "jstrieb/github-stats"
[master adc985c] Update generated files
 2 files changed, 33 insertions(+), [12](https://github.com/tanjuntao/github-stats/runs/6331838497?check_suite_focus=true#step:7:12)3 deletions(-)
remote: Permission to tanjuntao/github-stats.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/tanjuntao/github-stats/': The requested URL returned error: 403
Error: Process completed with exit code 128.
```

I don't get where the problem comes from, would you please provide some suggestions?

**Comment by jstrieb** [comment]
Hi @tanjuntao, thanks for taking the time to open this issue!

I have not seen this before, and do not have an answer off the top of my head. What is interesting is that I don't believe the final commit step actually uses your personal access token, so I don't think permissions for that are an issue. Have you tried re-running the action (or waiting until its next automatic run)? I'm curious if this is a fluke, or something that keeps happening.

**Comment by luchaoqi** [comment]
I am having the same issue here and re-running workflow doesn't work - will wait for the next automatic run to see if it still happens.

**Comment by tanjuntao** [comment]
Yes, I did re-run the action several times and each time I failed at the git commit step and got the same error message.

**Comment by briancpark** [comment]
I just started trying to use this as a new user. I see the same errors happening on my end as well ;(.

**Comment by jstrieb** [comment]
Hi all, thanks for chiming in! I figured out what the problem is.

It seems like GitHub changed the default permissions of the `GITHUB_TOKEN` environment variable available within Actions. I have just updated the Actions workflow to explicitly [use `write` permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token) for the token, so if you use the latest version of the actions workflow, it should work with no further changes. There is also a way to change the default token permissions from the repository settings.

In other words, this is fixed in the latest version of the repo. But for you in this thread who already have a stale copy, there are two ways to fix this, and you can pick either one:

- Regenerate a copy of the repository from the template and follow the steps with the latest version of the repo.
   - Alternatively, copy the newly-updated [`.github/workflows/main.yml`](https://github.com/jstrieb/github-stats/blob/master/.github/workflows/main.yml) file into your version of that file in your copy of this repository.
- Change the default permission of the token (without modifying the workflow).
   1. Go to `Repository Settings > Actions > General` (available here, where `username` is replaced with your username: <https://github.com/username/github-stats/settings/actions>). 
   2. Change the "Workflow Permissions" to "read and write permission"
       ![image](https://user-images.githubusercontent.com/7355528/167309714-28654232-5407-4b09-81e0-167ad397deca.png)

**Comment by luchaoqi** [comment]
The problem is solved but I got another issue same as #21 and #35 using the manual run afterward.
```
Run git config --global user.name "jstrieb/github-stats"
[master 87bd302] Update generated files
 2 files changed, 72 insertions(+), 63 deletions(-)
To https://github.com/luchaoqi/github-stats
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/luchaoqi/github-stats'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Process completed with exit code 1.
```

**Comment by tanjuntao** [comment]
I got exactly the same problem as you, I solved it by just deleting my old github-stats repo and generated a new one from scratch, this worked for me. 🤣

**Comment by briancpark** [comment]
Hmm. For me, the auto update of generating the file again failed.... with the same error as before, even though I repulled the updated template.

**Comment by luchaoqi** [comment]
I tried totally deleting the repo and reconfiguring it again - solve the problem as of now for me.

**Comment by tanjuntao** [comment]
@briancpark Did you still fail at the initial commit step after re-generating an updated repo? If your problem is same as #30, you can just wait for some minutes and run the failed job again and it will work.

**Comment by briancpark** [comment]
No, I successfully generated after re-generating an updated repo. That initial run took under 5 minutes. I changed a few env variables and I waited over an hour, but it's still hanging on the next runs after that ;(

**Comment by tanjuntao** [comment]
Have no idea about that. From the `main.yml` under the `.github/workflows/`, the supported env variables are
``` yaml
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_FORKED_REPOS: true
```

Maybe you could check the names and values of your env variables first, and if there are no problems, then just wait for the author to give a suggestion. 

*Note: the values of env variables should be separated by a comma (if more than two), because they are split by Python `split()` function in `generated_images.py`:

``` python
    exclude_repos = os.getenv("EXCLUDED")
    excluded_repos = (
        {x.strip() for x in exclude_repos.split(",")} if exclude_repos else None
    )
    exclude_langs = os.getenv("EXCLUDED_LANGS")
    excluded_langs = (
        {x.strip() for x in exclude_langs.split(",")} if exclude_langs else None
    )
```

**Comment by briancpark** [comment]
Thanks for the suggestion. All I did was add `html,ipynb` to `EXCLUDED_LANGS`. But seems like undoing it doesn't fix the problem. I'll try to redo the whole process of deleting and creating a new repo later.

**Comment by seyfer** [comment]
this setting change as in the comment https://github.com/jstrieb/github-stats/issues/70#issuecomment-1120465688 actually solves an issue
