### ISSUE TITLE
Action Not Run

### ISSUE THREAD

**Issue by gaetan1903** [jstrieb/github-stats#8]
How Tu Run Action ? 

I've been added my ACCES_TOKEN in Secret , but i don't know how to run it

I've been already commit a simple message 

But Nothiing 

![image](https://user-images.githubusercontent.com/43904633/100320116-07252300-2fc1-11eb-9c42-eefe0ce6ea7d.png)

**Comment by jstrieb** [comment]
Hi, thanks for taking a look at the project!

It looks like you've enabled actions in "Settings," but you also need to enable this _specific_ action. To do that, hit the Actions tab:
![image](https://user-images.githubusercontent.com/7355528/100493830-10b9a280-3109-11eb-8a0e-c4295d3d1aca.png)

In that tab there should be a big green button to enable this action.

Hopefully that solves your problem!

**Comment by gaetan1903** [comment]
Thank you
