### ISSUE TITLE
Allow to exclude some languages

### ISSUE THREAD

**Issue by hoangvanthien** [jstrieb/github-stats#9]
Languages like "HTML" or "Jupyter Notebook" sometimes should not be shown in the stats because a notebook file may be very heavy. Anyway, I think there are folks who just want to hide some languages. Perhaps we can add a line to `github_stats.py` like [this](https://github.com/hoangvanthien/github-stats/blob/7c133c1aaeb64188184e64b8e30cfa9036e32552/github_stats.py#L318).

**Comment by jstrieb** [comment]
Hi, thanks for using the project and for the recommendation with a link to the relevant part of the code!

The latest several commits should fully address this issue. It is now possible to add a secret value that will cause some languages to be fully ignored.
